- id: convert-beginning-tabs
  name: Convert beginning tabs to space
  entry: convert-beginning-tabs
  language: python
  description: "Replace beginning tabs by spaces before committing"
  args: ["--tab-size", "4"]
  exclude: (Makefile|debian/rules|.gitmodules)(\.in)?$
- id: convert-beginning-spaces
  name: Convert beginning spaces to tabs
  entry: convert-beginning-spaces
  language: python
  description: "Replace beginning spaces by tabs before committing"
  args: ["--tab-size", "4"]
  exclude: (Makefile|debian/rules|.gitmodules)(\.in)?$
- id: convert-text-to-html
  name: Convert text to html
  entry: convert-text-to-html
  language: python
  description: "Convert text to html, where each line is a `<p>` element"
  args: ["--textfiles", "file1.txt, file2.txt"]
  additional_dependencies: ["dominate"]
- id: minify-json
  name: Minify JSON files
  entry: minify-json
  language: python
  description: Minify JSON files to remove excess whitespace
- id: prettify-json
  name: Prettify JSON files
  entry: prettify-json
  language: python
  description: Prettify JSON files with indents
  args: ["--indent", "2"]
