- id: convert-beginning-tabs
  name: Convert beginning tabs to space
  description: "Replace beginning tabs by space before committing"
  entry: convert-beginning-tabs
  language: python
  args: [--whitespaces-count, "4"]
  files: ""
  exclude: (Makefile|debian/rules|.gitmodules)(\.in)?$
